apiVersion: v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    app: javaapp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: podname
      labels:
        app: javaapp
    spec:
      image: asmathsulthana/mavenapplication:1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
 selector:
   app: javaapp
 type: NodePort
 ports:
   - port: 80
     targetPort: 8080
