apiVersion: v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    app: deployment
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      name: podname
      labels:
        app: deployment
    spec:
      image: asmathsulthana/mavenapplication:1
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
 selector:
   app: deployment
 type: NodePort
 ports:
   - port: 80
     targetPort: 8080
